export const icaoToModelMap: Record<string, string> = {
	F100: "Fokker 100",
	B461: "BAe 146-100",
	B462: "BAe 146-200",
	B463: "BAe 146-300",
	E290: "Embraer E190-E2",
	E295: "Embraer E195-E2",
	BCS1: "Airbus A220-100",
	BCS3: "Airbus A220-200",
	A310: "Airbus A310",
	A318: "Airbus A318",
	A319: "Airbus A319 Ceo",
	A19N: "Airbus A319 Neo",
	A320: "Airbus A320-100/200 Ceo",
	A321: "Airbus A321-100/200 Ceo",
	A20N: "Airbus A320-200 Neo",
	A21N: "Airbus A321-200 Neo",
	A330: "Airbus A330",
	A332: "Airbus A330-200",
	A333: "Airbus A330-300",
	A337: "Airbus A330-700 Beluga XL",
	A338: "Airbus A330-800 Neo",
	A339: "Airbus A330-900 Neo",
	A340: "Airbus A340",
	A342: "Airbus A340-200",
	A343: "Airbus A340-300",
	A345: "Airbus A340-500",
	A346: "Airbus A340-600",
	A35K: "Airbus A350-1000",
	A359: "Airbus A350-900",
	A388: "Airbus A380",
	B703: "Boeing 707-300",
	B712: "Boeing 717",
	B721: "Boeing 727-100",
	B722: "Boeing 727-200",
	B731: "Boeing 737-100",
	B732: "Boeing 737-200",
	B733: "Boeing 737-300",
	B734: "Boeing 737-400",
	B735: "Boeing 737-500",
	B736: "Boeing 737-600",
	B737: "Boeing 737-700",
	B738: "Boeing 737-800",
	B739: "Boeing 737-900",
	B741: "Boeing 747-100",
	B742: "Boeing 747-200",
	B743: "Boeing 747-300",
	B744: "Boeing 747-400",
	B748: "Boeing 747-8",
	B74R: "Boeing 747SR",
	B752: "Boeing 757-200",
	B753: "Boeing 757-300",
	B762: "Boeing 762-200",
	B763: "Boeing 767-300",
	B764: "Boeing 767-400",
	B772: "Boeing 777-200",
	B773: "Boeing 777-300",
	B77L: "Boeing 777-200 Freighter",
	B77W: "Boeing 777-300ER",
	B78X: "Boeing 787-10",
	B788: "Boeing 787-8",
	B789: "Boeing 787-9",
	B37M: "Boeing 737 MAX 7",
	B38M: "Boeing 737 MAX 8",
	B39M: "Boeing 737 MAX 9",
	B3XM: "Boeing 737 MAX 10",
	AN22: "Antonov AN-22",
	AN26: "Antonov AN-26",
	AN28: "Antonov AN-28 / PZL Miele M-28 Skytruck",
	AN30: "Antonov AN-30",
	AN32: "Antonov AN-32",
	AN38: "Antonov AN-38",
	A140: "Antonov AN-140",
	A124: "Antonov AN-124 Ruslan",
	A225: "Antonov AN-225",
	A148: "Antonov AN-148-100",
	A30B: "Airbus A300B2/B4/C4",
	A306: "Airbus A300-600",
	A3ST: "Airbus A300-600ST Beluga Freighter",
	AC68: "Gulfstream/Rockwell (Aero) Commander",
	AC90: "Gulfstream/Rockwell (Aero) Turbo Commander",
	A109: "Agusta A109",
	LOAD: "Ayres LM-200 Loadmaster",
	AN24: "Antonov AN-24",
	AN72: "Antonov AN-72 / AN-74",
	AN12: "Antonov AN-12",
	RJ1H: "Avro RJ100 Avroliner",
	RJ70: "Avro RJ70 Avroliner",
	RJ85: "Avro RJ85 Avroliner",
	AT43: "Aerospatiale/Alenia ATR 42-300 / 320",
	AT45: "Aerospatiale/Alenia ATR 42-500",
	AT72: "Aerospatiale/Alenia ATR 72",
	AT44: "Aerospatiale/Alenia ATR 42-400",
	ATP: "British Aerospace ATP",
	RX1H: "Avro RJX100",
	RX85: "Avro RJX85",
	BA11: "British Aerospace (BAC) One Eleven",
	B720: "Boeing 720B",
	B190: "Beechcraft 1900/1900C/1900D",
	BN2P: "Pilatus Britten-Norman BN-2A/B Islander",
	TRIS: "Pilatus Britten-Norman BN-2A Mk III Trislander",
	AJ27: "COMAC ARJ21",
	C919: "COMAC C919",
	CL60: "Canadair Challenger",
	GLEX: "Canadair Global Express",
	NOMA: "Government Aircraft Factories N22B / N24A Nomad",
	CL44: "Canadair CL-44",
	C750: "Cessna 750 Citation X",
	CRJ1: "Canadair Regional Jet 100",
	CRJ2: "Canadair Regional Jet 200",
	CRJ7: "Canadair Regional Jet 700",
	CRJ9: "Canadair Regional Jet 900",
	CRJX: "Canadair Regional Jet 1000",
	S210: "Aerospatiale (Sud Aviation) Se.210 Caravelle",
	C212: "CASA / IPTN 212 Aviocar",
	CN35: "CASA / IPTN CN-235",
	CVLP: "Convair CV-240/440",
	CVLT: "Convair CV-580",
	C46: "Curtiss C-46 Commando",
	DC10: "Douglas DC-10",
	D228: "Fairchild Dornier Do.228",
	D328: "Fairchild Dornier Do.328",
	DC3: "Douglas DC-3",
	DC6: "Douglas DC-6A/B/C",
	DC86: "Douglas DC-8-62",
	DC87: "Douglas DC-8-72",
	DC85: "Douglas DC-8-50",
	DC91: "Douglas DC-9-10",
	DC92: "Douglas DC-9-20",
	DC93: "Douglas DC-9-30",
	DC94: "Douglas DC-9-40",
	DC95: "Douglas DC-9-50",
	DC4: "Douglas DC-4",
	DC9: "Douglas DC-9",
	DH8A: "De Havilland Canada DHC-8-100 Dash 8 / 8Q",
	DH8B: "De Havilland Canada DHC-8-200 Dash 8 / 8Q",
	DH8C: "De Havilland Canada DHC-8-300 Dash 8 / 8Q",
	DH8D: "De Havilland Canada DHC-8-400 Dash 8Q",
	DHC7: "De Havilland Canada DHC-7 Dash 7",
	DHC4: "De Havilland Canada DHC-4 Caribou",
	DOVE: "De Havilland DH.104 Dove",
	HERN: "De Havilland DH.114 Heron",
	DHC3: "De Havilland Canada DHC-3 Otter / Turbo Otter",
	DHC2: "De Havilland Canada DHC-2 Beaver",
	DH2T: "De Havilland Canada DHC-2 Turbo-Beaver",
	DHC6: "De Havilland Canada DHC-6 Twin Otter",
	E170: "Embraer 170",
	E190: "Embraer 190",
	EC30: "Eurocopter EC.130",
	E75S: "Embraer 175 (Short wing)",
	E75L: "Embraer 175 (Long Wing)",
	E195: "Embraer 195",
	E120: "Embraer EMB.120 Brasilia",
	E110: "Embraer EMB.110 Bandeirnate",
	E135: "Embraer RJ135",
	E35L: "Embraer Legacy 600 / Legacy 650",
	E145: "Embraer RJ145 Amazon",
	F28: "Fokker F.28 Fellowship",
	F27: "Fokker F.27 Friendship / Fairchild F.27",
	F50: "Fokker 50",
	F70: "Fokker 70",
	J328: "Fairchild Dornier 328JET",
	G21: "Grumman G.21 Goose",
	G73T: "Grumman G.73 Turbo Mallard",
	G159: "Gulfstream Aerospace G-159 Gulfstream I",
	COUC: "Helio H-250 Courier / H-295 / 385 Super Courier",
	A748: "Hawker Siddeley HS.748",
	I114: "Ilyushin IL114",
	IL96: "Ilyushin IL96",
	IL62: "Ilyushin IL62",
	IL76: "Ilyushin IL76",
	IL18: "Ilyushin IL18",
	IL86: "Ilyushin IL86",
	JS31: "British Aerospace Jetstream 31",
	JS32: "British Aerospace Jetstream 32",
	JS41: "British Aerospace Jetstream 41",
	JU52: "Junkers Ju52/3M",
	L101: "Lockheed L-1011 Tristar",
	CONI: "Lockheed L-1049 Super Constellation",
	L410: "LET 410",
	L188: "Lockheed L-188 Electra",
	C130: "Lockheed L-182 / 282 / 382 (L-100) Hercules",
	MD11: "McDonnell Douglas MD11",
	MD80: "McDonnell Douglas MD80",
	MD81: "McDonnell Douglas MD81",
	MD82: "McDonnell Douglas MD82",
	MD83: "McDonnell Douglas MD83",
	MD87: "McDonnell Douglas MD87",
	MD88: "McDonnell Douglas MD88",
	MD90: "McDonnell Douglas MD90",
	B105: "Eurocopter (MBB) Bo.105",
	EXPL: "MD Helicopters MD900 Explorer",
	MI8: "MIL Mi-8 / Mi-17 / Mi-171 / Mil-172",
	MU2: "Mitsubishi Mu-2",
	N262: "Aerospatiale (Nord) 262",
	S601: "Aerospatiale SN.601 Corvette",
	S65C: "Eurocopter (Aerospatiale) SA365C / SA365N Dauphin 2",
	PC12: "Pilatus PC-12",
	PC6T: "Pilatus PC-6 Turbo Porter",
	P68: "Partenavia P.68",
	SB20: "Saab 2000",
	S58T: "Sikorsky S-58T",
	S61: "Sikorsky S-61",
	S76: "Sikorsky S-76",
	SF34: "Saab SF340",
	SH33: "Shorts SD.330",
	SH36: "Shorts SD.360",
	BELF: "Shorts SC-5 Belfast",
	SC7: "Shorts SC-7 Skyvan",
	CONC: "Aerospatiale/BAC Concorde",
	SU95: "Sukhoi Superjet 100-95",
	T204: "Tupolev Tu-204 / Tu-214",
	T134: "Tupolev Tu134",
	T154: "Tupolev Tu154",
	VISC: "Vickers Viscount",
	WW24: "Israel Aircraft Industries 1124 Westwind",
	YK42: "Yakovlev Yak 42",
	YK40: "Yakovlev Yak 40",
	Y12: "Harbin Yunshuji Y12",
	YS11: "NAMC YS-11",
};

export const airline_names: Record<string, string> = {
	U2: "easyjet",
	"1T": "Bulgarian Air Charter",
	Q5: "40-Mile Air",
	"4O": "Interjet",
	"7A": "Express Air Cargo",
	JY: "Air Turks and Caicos",
	JU: "Air Serbia",
	QH: "Kyrgyzstan",
	A8: "Benin Golf Air",
	RV: "Caspian Airlines",
	"1B": "Abacus International",
	W9: "Eastwind Airlines",
	"6U": "Air Ukraine",
	E4: "Aero Asia International",
	ZI: "Aigle Azur",
	AE: "Mandarin Airlines",
	OZ: "Ozark Air Lines",
	"8U": "Afriqiyah Airways",
	Q9: "Afrinat International Airlines",
	KI: "Adam Air",
	QB: "Georgian National Airlines",
	LD: "Air Hong Kong",
	UX: "Air Europa",
	NX: "Air Macau",
	ZV: "Air Midwest",
	HM: "Air Seychelles",
	AF: "Air France",
	SB: "Air Caledonie International",
	EH: "SAETA",
	ZW: "Air Wisconsin",
	GN: "Air Gabon",
	NQ: "Air Japan",
	VD: "SwedJet Airways",
	TT: "Tigerair Australia",
	"4N": "Air North Charter - Canada",
	NZ: "Eagle Airways",
	QM: "Air Malawi",
	ML: "Midway Airlines (1976–1991)",
	P8: "Pantanal Linhas Aéreas",
	BM: "BMI Regional",
	ZX: "Air Georgian",
	G8: "Gujarat Airways",
	"7T": "Tobruk Air",
	"6V": "Mars RK",
	NH: "All Nippon Airways",
	TZ: "ATA Airlines",
	"2Q": "Air Cargo Carriers",
	V7: "Volotea",
	AB: "Air Berlin",
	"4D": "Air Sinai",
	QN: "Air Armenia",
	AI: "Air India Limited",
	PJ: "Air Saint Pierre",
	SZ: "Air Southwest",
	"8C": "Shanxi Airlines",
	NF: "Air Vanuatu",
	ZB: "Monarch Airlines",
	CC: "Macair Airlines",
	RB: "Syrian Arab Airlines",
	TN: "Air Tahiti Nui",
	SW: "Air Namibia",
	AW: "Dirgantara Air Service",
	PE: "People's Viennaline",
	JM: "Jetstar Hong Kong Airways",
	"6G": "Air Wales",
	TX: "Transportes Aéreos Nacionales",
	IX: "Air India Express",
	BT: "Air Baltic",
	EL: "Ellinair",
	YW: "Air Nostrum",
	PX: "Air Niugini",
	G9: "Air Arabia",
	AC: "Air Canada",
	AP: "Air One",
	XT: "SkyStar Airways",
	UM: "Air Zimbabwe",
	S2: "Air Sahara",
	TC: "Air Tanzania",
	"2J": "Air Burkina",
	KM: "Air Malta",
	YT: "Air Togo",
	G4: "Allegiant Air",
	M3: "North Flying",
	O4: "Antrak Air",
	GB: "ABX Air",
	"8V": "Wright Air Service",
	"8T": "Air Tindi",
	JP: "Adria Airways",
	A3: "Aegean Airlines",
	"2K": "Aerogal",
	KD: "KD Avia",
	KO: "Alaska Central Express",
	VX: "Virgin America",
	KH: "Aloha Air Cargo",
	AA: "American Airlines",
	AX: "Trans States Airlines",
	AN: "Ansett Australia",
	"5W": "Astraeus",
	VV: "Aerosvit Airlines",
	WK: "Edelweiss Air",
	QQ: "Reno Air",
	FG: "Ariana Afghan Airlines",
	Y2: "Flyglobespan",
	SU: "Aeroflot Russian Airlines",
	"5Z": "VivaColombia",
	"5D": "DonbassAero",
	"1A": "Amadeus IT Group",
	JJ: "LATAM Brasil",
	PL: "Airstars",
	"8A": "Atlas Blue",
	GD: "Air Alpha Greenland",
	HT: "Aeromist-Kharkiv",
	J2: "Azerbaijan Airlines",
	U3: "Avies",
	"4Y": "Yute Air Alaska",
	"5A": "Alpine Air Express",
	W4: "Aero Services Executive",
	IZ: "Arkia Israel Airlines",
	M6: "Amerijet International",
	"4A": "Air Kiribati",
	EV: "ExpressJet",
	HP: "Phoenix Airways",
	VH: "Aeropostal Alas de Venezuela",
	AM: "Aeroméxico",
	TL: "Trans Mediterranean Airlines",
	OY: "Omni Air International",
	IW: "Wings Air",
	J6: "AVCOM",
	"2D": "Aero VIP",
	VB: "VIVA Aerobus",
	OE: "Asia Overnight Express",
	GV: "Aero Flight",
	JW: "Vanilla Air",
	"2B": "Aerocondor",
	"4C": "Aires, Aerovías de Integración Regional, S.A.",
	AR: "Aerolíneas Argentinas",
	AS: "Alaska Airlines, Inc.",
	OB: "Oasis International Airlines",
	HC: "Iceland Express",
	FO: "Airlines of Tasmania",
	OS: "Austrian Airlines",
	IQ: "Augsburg Airways",
	RU: "SkyKing Turks and Caicos Airways",
	MO: "Calm Air",
	GR: "Gemini Air Cargo",
	NO: "Neos",
	AU: "Austral Líneas Aéreas",
	AO: "Australian Airlines",
	AV: "Avianca - Aerovías del Continente Americano S.A.",
	A0: "Avianca Argentina",
	O6: "Avianca Brazil",
	K8: "Airlink Zambia",
	B9: "Air Bangladesh",
	HJ: "Hellas Jet",
	AK: "Air Bridge Carriers",
	D7: "FlyAsianXpress",
	DJ: "Polynesian Blue",
	I5: "AirAsia India",
	EX: "Air Santo Domingo",
	"3G": "Atlant-Soyuz Airlines",
	AZ: "Alitalia",
	ZE: "Líneas Aéreas Azteca",
	A2: "Cielos Airlines",
	R7: "Aserca Airlines",
	RX: "Aviaexpress",
	MQ: "American Eagle Airlines",
	ZS: "Sama Airlines",
	FF: "Airshop",
	VU: "Air Ivoire",
	BP: "Air Botswana",
	GS: "Tianjin Airlines",
	VT: "Air Tahiti",
	"3N": "Air Urga",
	VL: "Air VIA",
	FK: "Keewatin Air",
	G2: "Avirex",
	V8: "Iliamna Air Taxi",
	K6: "Khalifa Airways",
	VE: "C.A.I. Second",
	V5: "Royal Aruban Airlines",
	CA: "Air China",
	Q6: "Aero Condor Peru",
	"5F": "Fly One",
	QC: "Air Corridor",
	NV: "Air Central",
	CV: "Cargolux",
	CW: "Air Marshall Islands",
	ZA: "Interavia Airlines",
	AH: "Air Algérie",
	ER: "Astar Air Cargo",
	HO: "Juneyao Airlines",
	EN: "Air Dolomiti",
	NM: "Mount Cook Airlines",
	EE: "Aero Airlines",
	"4F": "Air City",
	EI: "Aer Lingus",
	E8: "Alpi Eagles",
	KY: "Air São Tomé and Príncipe",
	PC: "Pegasus Airlines",
	OF: "Transports et Travaux Aériens de Madagascar",
	FJ: "Fiji Airways",
	RC: "Atlantic Airways",
	NY: "Air Iceland",
	"2P": "Air Philippines",
	"2U": "Air Guinee Express",
	"0A": "Amber Air",
	DA: "Air Georgia",
	GL: "Miami Air International",
	LL: "Allegro",
	"5Y": "Atlas Air",
	GG: "Cargo 360",
	H9: "Izair",
	HD: "AIRDO",
	IP: "Atyrau Air Ways",
	QK: "Air Canada Jazz",
	KK: "Atlasjet",
	JS: "Air Koryo",
	KC: "Air Astana",
	LV: "Albanian Airlines",
	"3S": "Air Guyane Express",
	D4: "Alidaunia",
	"9I": "Thai Sky Airlines",
	XL: "Aerolane",
	A6: "Hongtu Airlines",
	TD: "Tulip Air",
	L8: "Air Luxor GB",
	LK: "Air Luxor",
	MK: "Air Mauritius",
	MD: "Air Madagascar",
	"9U": "Air Moldova",
	L9: "Teamline Air",
	A7: "Air Plus Comet",
	QO: "Origin Pacific Airways",
	MR: "Air Mauritanie",
	F4: "Albarka Air",
	AJ: "Aero Contractors",
	"8Y": "China Postal Airlines",
	OT: "Aeropelican Air Services",
	AD: "Azul Linhas Aéreas Brasileiras",
	QD: "Air Class Líneas Aéreas",
	QS: "Travel Service",
	AG: "",
	MC: "Air Mobility Command",
	RE: "Stobart Air",
	UU: "Air Austral",
	ZP: "Silk Way Airlines",
	"6K": "Asian Spirit",
	A5: "Hop!",
	QL: "Línea Aérea de Servicio Ejecutivo Regional",
	R3: "Yakutia Airlines",
	MV: "Armenian International Airways",
	"2O": "Air Salone",
	U8: "Armavia",
	BQ: "Baltia Air Lines",
	P5: "AeroRepública",
	BF: "Bluebird Cargo",
	"5L": "AeroSur",
	JR: "Aero California",
	Z3: "Avient Aviation",
	GM: "Air Slovakia",
	VW: "Aeromar",
	OR: "TUI Airlines Netherlands",
	CG: "Airlines PNG",
	TY: "Iberworld",
	FL: "AirTran Airways",
	TS: "Air Transat",
	EC: "Avialeasing Aviation Company",
	DW: "Aero-Charter Ukraine",
	U7: "USA Jet Airlines",
	"6R": "Alrosa Air Company",
	"6A": "Aviacsa",
	JZ: "Skyways Express",
	AQ: "MAP-Management and Planung",
	"3J": "Zip",
	SM: "Swedline Express",
	KJ: "British Mediterranean Airways",
	BX: "Coast Air",
	YE: "Aryan Cargo Express",
	VJ: "Vietjet Air",
	"3O": "Air Arabia Maroc",
	X9: "Avion Express",
	JD: "Beijing Capital Airlines",
	ID: "Interlink Airlines",
	BA: "British Airways",
	BG: "Biman Bangladesh Airlines",
	B4: "Bankair",
	WX: "CityJet",
	BZ: "Keystone Air Service",
	JA: "JetSMART",
	J4: "Jordan International Air Cargo",
	"8H": "BH Air",
	"4T": "Belair Airlines",
	UP: "Bahamasair",
	E6: "Bringer Air Cargo Taxi Aéreo",
	LZ: "Balkan Bulgarian Airlines",
	TH: "Transmile Air Services",
	BS: "British International Helicopters",
	PG: "Bangkok Airways",
	KF: "Blue1",
	JV: "Bearskin Lake Air Service",
	B3: "Bellview Airlines",
	BD: "BMI",
	WW: "WOW air",
	CH: "Bemidji Airlines",
	BO: "Bouraq Indonesia Airlines",
	BV: "Blue Panorama Airlines",
	"7R": "BRA-Transportes Aéreos",
	"8E": "Bering Air",
	B2: "Belavia Belarusian Airlines",
	BN: "Horizon Airlines",
	GQ: "Big Sky Airlines",
	V9: "Star1 Airlines",
	Y6: "Batavia Air",
	BU: "Buryat Airlines Aircompany",
	J8: "Berjaya Air",
	QW: "Blue Wings",
	SN: "Brussels Airlines",
	DB: "Brit Air",
	E9: "Boston-Maine Airways",
	NT: "Binter Canarias",
	"0B": "Blue Air",
	FB: "Bulgaria Air",
	"8N": "Barents AirLink",
	CJ: "CityFlyer Express",
	YB: "Borajet",
	BW: "Caribbean Airlines",
	"7N": "PAWA Dominicana",
	"5C": "CAL Cargo Air Lines",
	"3C": "RegionsAir",
	R9: "Camai Air",
	UY: "Cameroon Airlines",
	C6: "CanJet",
	CP: "Compass Airlines",
	"5T": "Canadian North",
	W2: "Canadian Western Airlines",
	"9K": "Cape Air",
	PT: "West Air Sweden",
	"2G": "Cargoitalia",
	W8: "Cargojet Airways",
	C8: "Chicago Express Airlines",
	"8B": "Caribbean Star Airlines",
	V3: "Carpatair",
	CX: "Cathay Pacific",
	KX: "Cayman Airways",
	"5J": "Cebu Pacific",
	"3B": "Central Connect Airlines",
	"9M": "Central Mountain Air",
	J7: "ValuJet Airlines",
	WE: "Thai Smile Airways",
	OP: "Chalk's International Airlines",
	MG: "Champion Air",
	"2Z": "Chang An Airlines",
	S8: "Skywise Airline",
	CI: "China Airlines",
	CK: "China Cargo Airlines",
	MU: "China Eastern Airlines",
	G5: "China Express Airlines",
	WH: "WebJet Linhas Aéreas",
	CZ: "China Southern Airlines",
	KN: "China United Airlines",
	XO: "LTE International Airways",
	"3Q": "China Yunnan Airlines",
	X7: "Chitaavia",
	QI: "Cimber Sterling",
	C7: "Rico Linhas Aéreas",
	C9: "Cirrus Airlines",
	CF: "City Airline",
	G3: "Gol Transportes Aéreos",
	CT: "Civil Air Transport",
	"6P": "Club Air",
	DQ: "Coastal Air",
	"9L": "Colgan Air",
	YD: "Cologne Air Transport GmbH",
	OH: "PSA Airlines",
	MN: "Comair",
	C5: "CommutAir",
	KR: "Comores Airlines",
	GJ: "Eurofly",
	DE: "Condor Flugdienst",
	CO: "Continental Express",
	CS: "Continental Micronesia",
	V0: "Conviasa",
	CM: "Copa Airlines",
	CQ: "Sunshine Express Airlines",
	XC: "Corendon Airlines",
	CD: "Corendon Dutch Airlines",
	SS: "Corsairfly",
	XK: "Corse Méditerranée",
	F5: "Cosmic Air",
	OU: "Croatia Airlines",
	"7C": "Jeju Air",
	QE: "Crossair Europe",
	CU: "Cubana de Aviación",
	CY: "Cyprus Airways",
	YK: "Cyprus Turkish Airlines",
	OK: "Czech Airlines",
	"8L": "Redhill Aviation",
	XG: "Clickair",
	WD: "WDL Aviation",
	DX: "DAT Danish Air Transport",
	ES: "DHL International",
	L3: "LTU Austria",
	D3: "Daallo Airlines",
	N2: "Kabo Air",
	H8: "Dalavia",
	"0D": "Darwin Airline",
	D5: "Dauair",
	DL: "Delta Air Lines",
	"2A": "Deutsche Bahn",
	"1I": "Sky Trek International Airlines",
	DH: "Independence Air",
	Z6: "Dniproavia",
	YU: "Dominair",
	DO: "Dominicana de Aviación",
	E3: "Domodedovo Airlines",
	D9: "Donavia",
	KA: "Dragonair, Hong Kong Dragon Airlines",
	KB: "Druk Air",
	DI: "Dba",
	"9A": "Eagle Express Air Charter",
	E1: "Everbread",
	"1C": "Electronic Data Systems",
	"1Y": "Electronic Data Systems",
	BR: "EVA Air",
	EY: "Etihad Airways",
	H7: "Eagle Air",
	QU: "Uganda Airlines",
	S9: "East African Safari Air",
	EA: "European Air Express",
	T3: "Eastern Airways",
	QF: "Sunstate Airlines",
	DK: "Eastland Air",
	MS: "Egyptair",
	LY: "El Al Israel Airlines",
	UZ: "El-Buraq Air Transport",
	EK: "Emirates Airlines",
	EM: "Empire Airlines",
	EU: "Empresa Ecuatoriana De Aviación",
	E0: "Eos Airlines",
	B8: "Eritrean Airlines",
	E7: "European Aviation Air Charter",
	OV: "SalamAir",
	ET: "Ethiopian Airlines",
	RZ: "Euro Exec Express",
	MM: "SAM Colombia",
	UI: "Eurocypria Airlines",
	K2: "Eurolot",
	"3W": "Euromanx Airways",
	"5O": "Europe Airpost",
	QY: "European Air Transport",
	EW: "Eurowings",
	EZ: "Sun Air of Scandinavia",
	JN: "Excel Airways",
	MB: "MNG Airlines",
	OW: "Executive Airlines",
	EO: "Hewa Bora Airways",
	U2: "United Feeder Service",
	DS: "easyJet Switzerland",
	IH: "Irtysh Air",
	EF: "Far Eastern Air Transport",
	FD: "Thai AirAsia",
	F6: "FaroeJet",
	F3: "Faso Airways",
	FX: "Federal Express",
	N8: "National Air Cargo dba National Airlines",
	"4S": "Finalair Congo",
	AY: "Finnair",
	FC: "Finncomm Airlines",
	FY: "Northwest Regional Airlines",
	"7F": "First Air",
	DP: "First Choice Airways",
	"8F": "Fischer Air",
	"8D": "Servant Air",
	B5: "Flightline",
	PA: "Pan American World Airways",
	RF: "Florida West International Airways",
	F2: "Fly Air",
	OJ: "Overland Airways",
	SH: "Fly Me Sweden",
	TE: "Skytaxi",
	LF: "FlyNordic",
	F7: "Flybaboo",
	BE: "Flybe",
	W3: "Switfair Cargo",
	VY: "Vueling Airlines",
	HK: "Four Star Aviation / Four Star Cargo",
	FH: "Futura International Airways",
	SJ: "Freedom Air",
	FP: "Servicios Aéreos de los Andes",
	F9: "Frontier Airlines",
	"2F": "Frontier Flying Service",
	FZ: "Flydubai",
	"9Y": "Fly Georgia",
	VK: "Virgin Nigeria Airways",
	GX: "Pacificair",
	Y5: "Pace Airlines",
	GT: "GB Airways",
	Z5: "GMG Airlines",
	"7O": "Galaxy Air",
	"1G": "Galileo International",
	GC: "Gambia International Airlines",
	G7: "GoJet Airlines",
	GA: "Garuda Indonesia",
	"4G": "Gazpromavia",
	A9: "Georgian Airways",
	ST: "Germania",
	"4U": "Germanwings",
	GP: "Palau Trans Pacific Airlines",
	GH: "Ghana Airways",
	G0: "Ghana International Airlines",
	GK: "JetStar Japan",
	DC: "Golden Air",
	G1: "Gorkha Airlines",
	ZK: "Great Lakes Airlines",
	IJ: "Spring Airlines Japan",
	G6: "Air Volga",
	J9: "Jazeera Airways",
	GF: "Gulf Air Bahrain",
	GY: "Tri-MG Intra Asia Airlines",
	H6: "Hageland Aviation Services",
	HR: "Hahn Air",
	HU: "Hainan Airlines",
	"1R": "Hainan Phoenix Information Systems",
	"2T": "Haiti Ambassador Airlines",
	"4R": "Hamburg International",
	X3: "Hapag-Lloyd Express (TUIfly)",
	HF: "Hapagfly",
	HB: "Harbor Airlines",
	HQ: "Thomas Cook Airlines",
	HA: "Hawaiian Airlines",
	BH: "Hawkair",
	HN: "Heavylift Cargo Airlines",
	JB: "Helijet",
	ZU: "Helios Airways",
	HW: "North-Wright Airways",
	"2L": "Helvetic Airways",
	UD: "Hex'Air",
	"5K": "Hi Fly",
	H5: "Mavial Magadan Airlines",
	HX: "Hong Kong Airlines",
	RH: "Republic Express Airlines",
	UO: "Hong Kong Express Airways",
	HH: "Hope Air",
	QX: "Horizon Air",
	H4: "Inter Island Airways",
	IK: "Lankair",
	II: "IBC Airways",
	"0C": "IBL Aviation",
	C3: "Independent Carrier (ICAR)",
	"1F": "INFINI Travel Information",
	"1U": "Polyot Sirena",
	IB: "Iberia Airlines",
	I2: "Iberia Express",
	FW: "Ibex Airlines",
	FI: "Icelandair",
	"6E": "IndiGo Airlines",
	IC: "Indian Airlines",
	I9: "Indigo Airlines",
	QZ: "Indonesia AirAsia",
	IO: "Indonesian Airlines",
	D6: "Interair South Africa",
	RS: "Sky Regional Airlines",
	"6I": "International Business Air",
	"3L": "Intersky",
	I4: "Interstate Airlines",
	IR: "Iran Air",
	EP: "Iran Aseman Airlines",
	IA: "Iraqi Airways",
	"2S": "Satgur Air Transport",
	CN: "Westward Airways",
	IF: "Islas Airways",
	WC: "Islena De Inversiones",
	"6H": "Israir",
	FS: "Servicios de Transportes Aéreos Fueguinos",
	GI: "Itek Air",
	XM: "J-Air",
	JC: "JAL Express",
	JO: "Jettime",
	MT: "Thomas Cook Airlines",
	"1M": "JSC Transport Automated Information Systems",
	JI: "Midway Airlines (1993–2003)",
	"3X": "Japan Air Commuter",
	JL: "Japan Airlines Domestic",
	EG: "Japan Asia Airways",
	NU: "Japan Transocean Air",
	O2: "Linear Air",
	"9W": "Jet Airways",
	QJ: "Jet Airways",
	PP: "Jet Aviation",
	"3K": "Jetstar Asia Airways",
	LS: "Jet2.com",
	B6: "JetBlue Airways",
	JF: "L.A.B. Flying Service",
	"0J": "Jetclub",
	SG: "Spicejet",
	JQ: "Jetstar Airways",
	JX: "Jett8 Airlines Cargo",
	R5: "Malta Air Charter",
	"6J": "Skynet Asia Airways",
	KW: "Wataniya Airways",
	WA: "Western Airlines",
	KL: "KLM",
	K4: "Kalitta Air",
	K9: "Krylo Airlines",
	RQ: "Kam Air",
	E2: "Rio Grande Air",
	V2: "Vision Airlines",
	KV: "Kavminvodyavia",
	M5: "Kenmore Air",
	KQ: "Kenya Airways",
	IT: "Tigerair Taiwan",
	Y9: "Kish Air",
	KP: "Kiwi International Air Lines",
	"7K": "Kogalymavia Air Company",
	"8J": "Komiinteravia",
	KE: "Korean Air",
	"7B": "Krasnojarsky Airlines",
	GW: "SkyGreece Airlines",
	KU: "Kuwait Airways",
	GO: "Kuzu Airlines Cargo",
	N5: "Skagway Air Service",
	R8: "Kyrgyzstan Airlines",
	YQ: "TAR Aerolineas",
	LR: "LACSA",
	KG: "LAI - Línea Aérea IAACA",
	LA: "LATAM Chile",
	"4M": "LATAM Argentina",
	PZ: "TAM Mercosur",
	LU: "LATAM Express",
	LP: "LATAM Peru",
	NI: "Portugalia",
	L5: "Lufttransport",
	LO: "LOT Polish Airlines",
	LT: "LongJiang Airlines",
	N6: "Nuevo Continente",
	QV: "Lao Airlines",
	L7: "Línea Aérea SAPSA",
	NG: "Lauda Air",
	LQ: "Lebanese Air Transport",
	LI: "Leeward Islands Air Transport",
	LN: "Libyan Arab Airlines",
	TM: "Linhas Aéreas de Moçambique",
	JT: "Lion Mentari Airlines",
	LM: "Livingston",
	LB: "Lloyd Aéreo Boliviano",
	LC: "Varig Logística",
	HE: "Luftfahrtgesellschaft Walter",
	LH: "Lufthansa Cargo",
	CL: "Lufthansa CityLine",
	L1: "Lufthansa Systems",
	DV: "Nantucket Airlines",
	LG: "Luxair",
	"5V": "Lviv Airlines",
	L2: "Lynden Air Cargo",
	L4: "Lynx Aviation",
	Z8: "Línea Aérea Amaszonas",
	MJ: "Mihin Lanka",
	Q2: "Maldivian (airline)",
	OD: "Malindo Airways",
	M7: "Tropical Airways",
	MH: "Malaysia Airlines",
	IN: "NAM Air",
	OM: "MIAT Mongolian Airlines",
	DM: "Maersk",
	W5: "Mahan Air",
	M2: "MHS Aviation GmbH",
	TF: "Malmö Aviation",
	MA: "Malév Hungarian Airlines",
	RI: "Mandala Airlines",
	JE: "Mango",
	MP: "Martinair",
	Q4: "Starlink Aviation",
	"8M": "Myanmar Airways International",
	MY: "Midwest Airlines (Egypt)",
	MW: "Mokulele Airlines",
	"7M": "Mayair",
	M8: "Mekong Airlines",
	IM: "Menajet",
	IG: "Meridiana",
	MZ: "Merpati Nusantara Airlines",
	YV: "Mesa Airlines",
	XJ: "Thai AirAsia X",
	MX: "Mexicana de Aviación",
	ME: "Middle East Airlines",
	YX: "Midwest Airlines",
	M4: "Mistral Air",
	"2M": "Moldavian Airlines",
	"8I": "Myway Airlines",
	YM: "Montenegro Airlines",
	"5M": "Sibaviatrans",
	"3R": "Moskovia Airlines",
	M9: "Motor Sich",
	N4: "Nordwind Airlines",
	VZ: "Thai Vietjet Air",
	UB: "Myanma Airways",
	"6N": "Nordic Regional",
	P9: "Peruvian Airlines",
	UE: "Transeuropean Airlines",
	N7: "National Airlines",
	NA: "North American Airlines",
	"9O": "National Airways Cameroon",
	NC: "Northern Air Cargo",
	CE: "Nationwide Airlines",
	"1N": "Navitaire",
	RA: "Nepal Airlines",
	EJ: "New England Airlines",
	"2N": "Yuzhmashavia",
	HG: "Niki",
	KZ: "Nippon Cargo Airlines",
	DD: "Nok Air",
	"5N": "Nordavia",
	JH: "Nordeste Linhas Aéreas Regionais",
	N9: "North Coast Aviation",
	NW: "Northwest Airlines",
	J3: "Northwestern Air",
	DY: "Norwegian Air Shuttle",
	D8: "Norwegian Air International",
	DU: "Norwegian Long Haul",
	BJ: "Nouvel Air Tunisie",
	O9: "Nova Airline",
	VQ: "Novo Air",
	NK: "Spirit Airlines",
	UQ: "O'Connor Airlines",
	O8: "Oasis Hong Kong Airlines",
	VC: "Voyageur Airways",
	OA: "Olympic Airlines",
	WY: "Oman Air",
	"8Q": "Princess Air",
	R2: "Orenburg Airlines",
	OX: "Orient Thai Airlines",
	OL: "OLT Express Germany",
	ON: "Our Airline",
	O7: "Ozjet Airlines",
	PV: "St Barth Commuter",
	"9Q": "PB Air",
	PU: "PLUNA",
	U4: "PMTair",
	BL: "Pacific Airlines",
	"8P": "Pacific Coastal Airlines",
	Q8: "Pacific East Asia Cargo Airlines",
	LW: "Sun Air International",
	PK: "Pakistan International Airlines",
	PF: "Palestinian Airlines",
	NR: "Pamir Airways",
	PN: "Pan American Airways",
	I7: "Paramount Airways",
	P3: "Passaredo Transportes Aéreos",
	KS: "Peninsula Airways",
	Z2: "EZD",
	PR: "Philippine Airlines",
	"9R": "Phuket Air",
	PI: "Sun Air (Fiji)",
	"9E": "Pinnacle Airlines",
	PO: "Polar Air Cargo",
	PH: "Polynesian Airlines",
	PD: "Porter Airlines",
	BK: "Potomac Air",
	PW: "Precision Air",
	TO: "Transavia France",
	FE: "Primaris Airlines",
	"8W": "Private Wings Flugcharter",
	P6: "Privilege Style Líneas Aéreas",
	P0: "Proflight Zambia",
	FV: "Rossiya",
	QR: "Qatar Airways",
	R6: "RACSA",
	"1D": "Radixx Solutions International",
	V4: "Vieques Air Link",
	FN: "Regional Air Lines",
	ZL: "Regional Express",
	P7: "Russian Sky Airlines",
	RW: "Republic Airlines",
	RL: "Royal Phnom Penh Airways",
	SL: "Thai Lion Mentari",
	GZ: "Air Rarotonga",
	RR: "Royal Air Force",
	AT: "Royal Air Maroc",
	R0: "Royal Airlines",
	BI: "Royal Brunei Airlines",
	RJ: "Royal Jordanian",
	RK: "Royal Khmer Airlines",
	WR: "WestJet Encore",
	WB: "Rwandair Express",
	"7S": "Ryan Air Service",
	RD: "Ryan International Airlines",
	FR: "Ryanair",
	YS: "Régional Compagnie Aérienne Européenne",
	TR: "Tigerair Singapore",
	"6Y": "Smartlynx Airlines",
	"7E": "Sylt Air GmbH",
	S4: "SATA International",
	SA: "South African Airways",
	W7: "Western Pacific Airlines",
	NL: "Shaheen Air International",
	SK: "SAS Braathens",
	UG: "Tuninter",
	S7: "S7 Airlines",
	BB: "Seaborne Airlines",
	K5: "SeaPort Airlines",
	UL: "SriLankan Airlines",
	SY: "Sun Country Airlines",
	I6: "Sky Eyes",
	"7G": "Star Flyer",
	FA: "Safair",
	HZ: "Sat Airlines",
	SP: "SATA Air Acores",
	"8S": "Scorpio Aviation",
	ZY: "Sky Airlines",
	SQ: "Singapore Airlines Cargo",
	SI: "Skynet Airlines",
	XS: "SITA",
	FT: "Siem Reap Airways",
	SX: "Skybus Airlines",
	S6: "Star Air",
	D2: "Severstal Air Company",
	"5G": "Skyservice Airlines",
	SD: "Sudan Airways",
	SV: "Saudia",
	WN: "Southwest Airlines",
	A4: "Southern Winds Airlines",
	WG: "Sunwing Airlines",
	LX: "Swiss International Air Lines",
	SR: "Swissair",
	WV: "Swe Fly",
	XQ: "SunExpress",
	AL: "TransAVIAexport Airlines",
	E5: "Samara Airlines",
	SC: "Shandong Airlines",
	"9C": "Spring Airlines",
	"3U": "Sichuan Airlines",
	FM: "Shanghai Airlines",
	ZH: "Shenzhen Airlines",
	"7L": "Sun D'Or",
	NE: "SkyEurope",
	SO: "Sunshine Airlines",
	JK: "Spanair",
	"1Z": "Sabre Pacific",
	"1S": "Sabre",
	"1H": "Siren-Travel",
	"1Q": "Sirena",
	"1K": "Sutra",
	"2C": "SNCF",
	S0: "Slok Air Gambia",
	S3: "Santa Barbara Airlines",
	H2: "Sky Airline",
	OO: "SkyWest Airlines",
	BC: "Skymark Airlines",
	LJ: "Sierra National Airlines",
	MI: "SilkAir",
	"6Q": "Slovak Airlines",
	PY: "Surinam Airways",
	NB: "Sterling Airlines",
	IE: "Solomon Airlines",
	"6W": "Saratov Airlines Joint Stock Company",
	S5: "Trast Aero",
	R1: "Sirin",
	O3: "SF Airlines",
	EQ: "TAME",
	TP: "TAP Portugal",
	TU: "Tunisair",
	"3V": "TNT Airways",
	T2: "Thai Air Cargo",
	TQ: "Tandem Aero",
	ZT: "Titan Airways",
	DG: "Tigerair Philippines",
	TG: "Thai Airways International",
	TK: "Turkish Airlines",
	T7: "Twin Jet",
	"3P": "Tiara Air",
	TI: "Tol-Air Services",
	BY: "Thomson Airways",
	PM: "Tropic Air",
	QT: "TAMPA",
	K3: "Taquan Air Services",
	GE: "TransAsia Airways",
	HV: "Transavia Holland",
	VR: "TACV",
	T9: "Thai Star Airlines",
	"9T": "Transwest Air",
	UN: "Transaero Airlines",
	T5: "Turkmenhovayollary",
	T6: "Tavrey Airlines",
	TW: "T'way Air",
	"6B": "TUIfly Nordic",
	DT: "TAAG Angola Airlines",
	SF: "Tassili Airlines",
	TJ: "Tradewind Aviation",
	"1E": "Travelsky Technology",
	"2H": "Thalys",
	"1L": "Open Skies Consultative Commission",
	RO: "Tarom",
	"3T": "Turan Air",
	T4: "TRIP Linhas Aéreas",
	L6: "Tbilaviamsheni",
	XN: "XpressAir",
	VO: "Tyrolean Airways",
	U5: "USA3000 Airlines",
	UA: "United Airlines",
	"4H": "United Airways",
	U6: "Ural Airlines",
	UF: "UM Airlines",
	"6Z": "Ukrainian Cargo Airways",
	"5X": "United Parcel Service",
	US: "US Airways",
	UH: "US Helicopter",
	UT: "UTair Aviation",
	HY: "Uzbekistan Airways",
	PS: "Ukraine International Airlines",
	VA: "Viasa",
	VF: "Valuair",
	"0V": "Vietnam Air Services Company (VASCO)",
	VN: "Vietnam Airlines",
	NN: "VIM Airlines",
	"2R": "Via Rail Canada",
	Y4: "Volaris",
	VI: "Volga-Dnepr Airlines",
	TV: "Virgin Express",
	VS: "Virgin Atlantic Airways",
	ZG: "Viva Macau",
	XF: "Vladivostok Air",
	VM: "Viaggio Air",
	"9V": "Vipair Airlines",
	RG: "VRG Linhas Aéreas",
	VP: "VASP",
	VG: "VLM Airlines",
	WT: "Wasaya Airways",
	"2W": "Welcome Air",
	WZ: "West African Airlines",
	YH: "West Caribbean Airways",
	"8O": "West Coast Air",
	WS: "WestJet",
	XP: "Xtra Airways",
	WF: "Widerøe",
	IV: "Wind Jet",
	"7W": "Windrose Air",
	"8Z": "Wizz Air Bulgaria",
	W6: "Wizz Air",
	WO: "World Airways",
	"1P": "Worldspan",
	MF: "Xiamen Airlines",
	SE: "XL Airways France",
	YL: "Yamal Airlines",
	Y8: "Yangtze River Express",
	Y0: "Yellow Air Taxi/Friendship Airways",
	IY: "Yemenia",
	C4: "Zimex Aviation",
	Q3: "Zambian Airways",
	Z4: "Zoom Airlines",
};
